# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Definition Date')),
            ],
            options={
                'verbose_name': 'Analyse',
                'verbose_name_plural': 'Analysis',
            },
        ),
        migrations.CreateModel(
            name='AnalyseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Analyse Group',
                'verbose_name_plural': 'Analyse Groups',
            },
        ),
        migrations.CreateModel(
            name='AnalyseState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Analyse Type',
                'verbose_name_plural': 'Analyse Types',
            },
        ),
        migrations.CreateModel(
            name='AnalyseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.AnalyseGroup')),
            ],
            options={
                'verbose_name': 'Analyse Type',
                'verbose_name_plural': 'Analyse Types',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('governmental', models.BooleanField(default=False, verbose_name='Government Agency?')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('relation', models.SmallIntegerField(choices=[(1, 'Self'), (2, 'Father'), (3, 'Mother')], verbose_name='Patient Relation')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='MediumType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'Medium Type',
                'verbose_name_plural': 'Medium Types',
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Analyse Method',
                'verbose_name_plural': 'Analyse Methods',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcno', models.CharField(max_length=11, verbose_name='TC No')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('newborn', models.BooleanField(default=False, verbose_name='Is newborn?')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('sex', models.SmallIntegerField(choices=[(1, 'Female'), (2, 'Male')], verbose_name='Sex')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('relation', models.SmallIntegerField(choices=[(1, 'Self'), (2, 'Father'), (3, 'Mother')], verbose_name='Patient Relation')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='PatientAdmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.Institution')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.Patient')),
            ],
            options={
                'verbose_name': 'Patient Admission',
                'verbose_name_plural': 'Patient Admissions',
            },
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
                ('medium', models.ManyToManyField(to='lab.MediumType')),
            ],
            options={
                'verbose_name': 'Sample Type',
                'verbose_name_plural': 'Sample Types',
            },
        ),
        migrations.AddField(
            model_name='analysestate',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.AnalyseType'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.PatientAdmission'),
        ),
    ]
