# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseStateDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.AnalyseType')),
            ],
            options={
                'verbose_name_plural': 'Analyse State Definitions',
                'verbose_name': 'Analyse State Definition',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name_plural': 'Institutions',
                'verbose_name': 'Institution',
            },
        ),
        migrations.AlterModelOptions(
            name='analysestate',
            options={'verbose_name': 'Analyse State Entry', 'verbose_name_plural': 'Analyse State Entries'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Institution', 'verbose_name_plural': 'Institutions'},
        ),
        migrations.RenameField(
            model_name='analysestate',
            old_name='name',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='surname',
        ),
        migrations.AddField(
            model_name='analyse',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='lab.AnalyseType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysestate',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.Analyse'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.Institution'),
        ),
    ]
