# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-21 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_doctor_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysetype',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
