# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20161221_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='If left blank, an institution record will be created for this doctor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.Institution', verbose_name='Institution'),
        ),
    ]
