# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
