# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_auto_20161222_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='key',
            new_name='name',
        ),
    ]
